services:

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    restart: unless-stopped
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: unless-stopped
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"

  payment-service:
    build: ./payment-service
    container_name: payment-service
    restart: unless-stopped
    depends_on:
      - postgres-db
      - eureka-server
    environment:
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "9091:9091"

volumes:
  pgdata: