server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: payment-service-route
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

      default-filters:
        - AddRequestHeader=X-INTERNAL-GATEWAY,true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

jwt:
  secret: ${JWT_SECRET:thisIsADefaultSecretKeyForDevOnlyChangeInProd}